---
# This playbook will setup a docker-ized content host deployment
# environment on the target system(s).
# After completion, a RHEL 7.4 docker image will be available
# and the git repo will be located at /root/content-host-d
- hosts: beaker
  remote_user: root
  tasks:
  - name: Install Docker
    package: name=docker state=latest
  - service: name=docker state=started enabled=yes

  - name: Install python pip
    easy_install: name=pip
  - name: Install docker-py
    pip: name=docker-py state=latest

  - name: Install git
    package: name=git state=present
  - name: Clone content host repo
    git:
      repo : https://github.com/JacobCallahan/content-host-d.git
      version : rhel74
      dest : /root/content-host-d

  - name: Build RHEL 7.4 content host image
    docker_image:
      path: /root/content-host-d
      name: ch-d
      tag: rhel74
